### ISSUE TITLE
add setting for IkCulling to only kick on when a certain number of users are in the session

### ISSUE THREAD

**Issue by epicEaston197** [KyuubiYoru/IkCulling#2]
basically I only want this feature to be active whenever a certain number of users are in the session maybe it could be configurable let's say the max is five people maybe six maybe eight I don't know but if the number is less than that then it won't cull IK

**Comment by KyuubiYoru** [comment]
I can add a config option for this.

**Comment by KyuubiYoru** [comment]
Added option for this in 1.4.0
